#!/bin/bash

# sleep will be required at the login but not by the cron task
if [ "$1" != "nosleep" ]; then
	sleep 5
fi

# We modify all brightness settings (acpi and graphic cards)
for BASE in $(/bin/ls -d1 /sys/class/backlight/*); do
	if [ $? -eq 0 ]; then
		RES=$(($(cat $BASE/max_brightness) / 2))
		echo "echo $RES > $BASE/brightness"
	fi
done
