#!/bin/sh
# ROLE:   Moves the contents of /var/log, /var/cache, /var/tmp and /home/.cache to RAM.
#         Then keeps it there until reload or stop, when it copies the contents back to permanent storage.
# SOURCE: http://www.debian-administration.org/articles/661, https://sites.google.com/site/linuxpendrive/rorootfs, http://wiki.debian.org/ReadonlyRoot
# NOTE:   used by /etc/systemd/system/rwramd.service
# DEPENDENCIES : awk, du, free, head, mount, umount
# USAGE : systemctl {start|stop|status|reload} rwramd

source /usr/lib/rwram

NAME="rwramd"
MODE="0755"

CACHE_RAM="/var/cache"
CACHE_HDD="/mnt/var/cache.permanent/"
HOME_CACHE_RAM="/home/$USER/.cache"
HOME_CACHE_HDD="/mnt/home/$USER/.cache.permanent/"
LOG_RAM="/var/log"
LOG_HDD="/mnt/var/log.permanent/"
TMP_RAM="/var/tmp"
TMP_HDD="/mnt/var/tmp.permanent/"


#Execute options
case $1 in
	start)
		if [ ! -f /var/lock/$NAME.lock ]; then
			$1 $LOG_RAM        $LOG_HDD
		
			echo Log done
			$1 $CACHE_RAM      $CACHE_HDD
			$1 $TMP_RAM        $TMP_HDD
		fi
		;;
	stop)
		if [ -f /var/lock/$NAME.lock ]; then
			echo $1 $LOG_RAM        $LOG_HDD
			$1 $LOG_RAM        $LOG_HDD
		
			echo Log done
			$1 $CACHE_RAM      $CACHE_HDD
			$1 $TMP_RAM        $TMP_HDD
			rm -r /var/lock/$NAME.lock
		fi
		;;
	reload)
		if [ -f /var/lock/$NAME.lock ]; then
			$1 $LOG_RAM        $LOG_HDD
		
			echo Log done
			$1 $CACHE_RAM      $CACHE_HDD
			$1 $TMP_RAM        $TMP_HDD
		fi
		;;
	*)
		echo "Usage : systemctl {start|stop|status|reload} $0"
		;;
esac
