#!/bin/bash
#
# This script is executed whenever your appliance boots.  Here you can add
# commands to be executed before the system enters the first runlevel.  This
# could include loading kernel modules, starting daemons that aren't managed
# by init files, asking questions at the console, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance (oem =
# disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

# start our pm-profile
/usr/lib/pm-profiler/enable-profile opencpn

# force the processor's cores freq
FREQ=$(cpupower frequency-info -l |tail -n 1 |cut -d " " -f 1) # we assume that all cores have the same limit than core 0
cpupower -c all frequency-set -u $FREQ # we don't touch the governor, pm-profiles does it

# we stop / disable unwanted services
if [ -n $(service --status-all |grep sshd | awk '{print $4}') ]; then
    systemctl stop sshd.service
    systemctl disable sshd.service
fi

if [ -n $(service --status-all |grep bluetooth | awk '{print $4}') ]; then
	systemctl stop bluetooth.service
	systemctl disable bluetooth.service
fi

# we need to set the right permissions or our user can't change
# the screen brightness without login as root.
for FILE in $(/bin/ls -d1 /sys/class/backlight/*/brightness); do
    if [ $? -eq 0 ]; then
		chown root:users $FILE
		chmod g+w $FILE
	fi
done

# we run our script at the lxsession start
# added here to "survive" the install
if [ $(grep -c "/usr/bin/brightness" /etc/xdg/lxsession/LXDE/autostart) -eq 0 ]; then
	echo "/usr/bin/brightness" >> /etc/xdg/lxsession/LXDE/autostart
fi

if [ $(sysctl -n vm.dirty_writeback_centisecs) != 1500 ] ; then
	sysctl -w vm.dirty_writeback_centisecs=1500
fi

if [ $(sysctl -n vm.dirty_background_ratio) != 20 ] ; then
	sysctl -w vm.dirty_background_ratio=20
fi

if [ $(sysctl -n vm.dirty_ratio) != 20 ] ; then
	sysctl -w vm.dirty_ratio=20
fi